# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 10 Nov 2018 11:29:53 +0000
*	@admin	16
*	@ALL	1
for_admin:*	@ALL	0
en:*	@lvl%5f2	8
