<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tester_admin
 * Date: Sat, 09 Mar 2019 11:43:23 +0000
 */

$conf['title'] = 'INREM Knowledge Repo';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['toptoclevel'] = '4';
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['updatecheck'] = 0;
$conf['renderer_xhtml'] = 'xbr';
$conf['plugin']['multilingual']['enabled_langs'] = 'en, hi, kn';
$conf['plugin']['showpageafterlogin']['page_after_login'] = 'english:start';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;

// end auto-generated content
//
