<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: abrar
 * Date: Wed, 30 Jan 2019 08:50:37 +0000
 */

$conf['title'] = 'INREM Knowledge Repo';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['tocminheads'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['updatecheck'] = 0;
$conf['renderer_xhtml'] = 'xbr';
$conf['plugin']['multilingual']['enabled_langs'] = 'en, hi, kn';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;

// end auto-generated content
