<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: abrar
 * Date: Fri, 25 Jan 2019 09:50:03 +0000
 */

$conf['title'] = 'INREM Knowledge Repo';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['updatecheck'] = 0;
$conf['plugin']['multilingual']['enabled_langs'] = 'en, hi, kn';
$conf['plugin']['multilingual']['start_redirect'] = 1;
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;

// end auto-generated content
